export enum SortBy {
  FEATURED = "FEATURED",
  NEWEST = "NEWEST",
  PRICE_HIGHLOW = "PRICE_HIGHLOW",
  PRICE_LOWHIGH = "PRICE_LOWHIGH",
  QUANTITY_HIGHLOW = "QUANTITY_HIGHLOW",
  QUANTITY_LOWHIGH = "QUANTITY_LOWHIGH",
}
